pipeline {
    agent {
            label 'node-1'
          }
    stages {
        stage('Example') {
            steps {
                '''
               sudo yum install httpd -y    
                '''
            }
        }
    }
}
