pipeline {
    agent {
        label 'node-1'
    }
    stages {
        stage('Install HTTPD') {
            steps {
                sh '''
                    sudo yum install httpd -y
                    sudo cp /root/bluestacks/index.html /var/www/html
                    sudo systemctl start httpd
                '''
            }
        }
    }
}

